<?php

declare(strict_types=1);

use Symfony\Config\LexikJwtAuthenticationConfig;

return static function (LexikJwtAuthenticationConfig $lexikJwtAuthentication) {
    // public and private keys generated by `php bin/console lexik:jwt:generate-keypair`
    // after setting up this config (it needs it to know where to store beforehand)

    $lexikJwtAuthentication
        ->publicKey('%kernel.project_dir%/config/jwt/public.pem')
        ->secretKey('%kernel.project_dir%/config/jwt/private.pem')
        ->passPhrase('%env(JWT_PASSPHRASE)')
        ->tokenTtl(3600)
    ;
};
